In [42]:
import netCDF4 as nc
import numpy as np

In [43]:
ref_path = '/glade/work/xiugao/fates-input/vaira-1pt/cheyenne-alt.nc'
targ_path = '/glade/work/xiugao/fates-input/vaira-1pt/derecho-default.nc'

In [45]:
#open NetCDF file
#r+ with write access while r read-only
with nc.Dataset(targ_path, 'r+') as targ, nc.Dataset(ref_path,'r') as ref:
    for var_name in targ.variables:
        if var_name in ref.variables:
            var_ref  = ref.variables[var_name][:]
            var_targ = targ.variables[var_name][:]
            #check if the shapes are the same
            if var_ref.shape == var_targ.shape:
                diff = np.where(var_ref != var_targ)
                #modify value in the target where it differes from the reference
                var_targ[diff] = var_ref[diff]
                #update variable in target
                targ.variables[var_name][:] = var_targ
            else:
                print(f"Variable '{var_name}' has different shapes in the files.")
        else:
            print(f"Variable '{var_name}' not found in the reference file.")


    

Variable 'fates_history_sizeclass_bin_edges' has different shapes in the files.
Variable 'fates_landuseclass_name' not found in the reference file.
Variable 'fates_maxpatches_by_landuse' not found in the reference file.
Variable 'fates_maintresp_reduction_upthresh' not found in the reference file.
Variable 'fates_mort_upthresh_cstarvation' not found in the reference file.
Variable 'fates_phen_drought_threshold' has different shapes in the files.
Variable 'fates_phen_fnrt_drop_fraction' not found in the reference file.
Variable 'fates_phen_mindaysoff' has different shapes in the files.
Variable 'fates_phen_moist_threshold' has different shapes in the files.
Variable 'fates_seed_dispersal_fraction' not found in the reference file.
Variable 'fates_seed_dispersal_max_dist' not found in the reference file.
Variable 'fates_seed_dispersal_pdf_scale' not found in the reference file.
Variable 'fates_seed_dispersal_pdf_shape' not found in the reference file.
Variable 'fates_trs_repro_alloc_a' no

IndexError: too many indices for array

In [59]:
targ = nc.Dataset(targ_path)
var = targ.variables['fates_stoich_nitr'][:]
var[:]
shp = var.shape

ref = nc.Dataset(ref_path)
var1 = ref.variables['fates_stoich_nitr'][:]
shp1 = var.shape
print(shp1)

dif = np.where(var != var1)
print(var[dif])
print(var1[dif])
print(dif)
#var[dif] = var1[dif]
print(var)
print(var1)



(4, 2)
[0.04  0.04  0.024 0.024]
[0.0184375 0.0122662 0.015     0.015    ]
(array([0, 0, 1, 1]), array([0, 1, 0, 1]))
[[4.0e-02 4.0e-02]
 [2.4e-02 2.4e-02]
 [1.0e-08 1.0e-08]
 [4.7e-03 4.7e-03]]
[[1.84375000e-02 1.22662037e-02]
 [1.50000000e-02 1.50000000e-02]
 [1.00000000e-08 1.00000000e-08]
 [4.70000000e-03 4.70000000e-03]]
